services:
  backend:
    build:
      context: ./orderup
      dockerfile: Dockerfile
    container_name: orderup-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - JWT_SECRET=${JWT_SECRET:-defaultSecretKeyShouldBeAtLeast32Characters}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - orderup-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: orderup-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - orderup-network
    restart: unless-stopped

networks:
  orderup-network:
    driver: bridge 